### ISSUE TITLE
Latest version crashes when running

### ISSUE THREAD

**Issue by shavanni** [xbmc-catchuptv-au/plugin.video.abc_iview#3076] opened 2017-09-01 11:36 UTC
Using SPMC the latest version 1.8.4 crashes when opening the add-on. 
Rolled back to 1.8.2 for it to work again

**Comment by andybotting** [comment] 2017-09-01 11:37
Can you provide *any* more details than this?

**Comment by andybotting** [comment] 2017-09-01 11:46
OK, I've replicated it. I'll work on a fix, but this is due to SPMC having an old version of Python bundled. If you could use Kodi v17 this would work.

**Comment by andybotting** [comment] 2017-09-01 12:45
Fix now committed in the pycaptions module v0.5.6. It is now available in the repository.

Thanks for reporting.

**Closed by andybotting** 2017-09-01 12:45 UTC

**Comment by shavanni** [comment] 2017-09-01 22:16
Hi, I've tried updating. Issue still ocurrs

**Comment by andybotting** [comment] 2017-09-01 22:55
Can you confirm you have pycaptions v0.5.6 installed? The issue is not in the iView add-on

**Comment by shavanni** [comment] 2017-09-02 21:20
Pycaptions updated today. All good. Thanks

**Comment by andybotting** [comment] 2017-09-04 22:27
Thanks @shavanni
